name: tmux_3.0_linux_amd64

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get install -y libevent-dev ncurses-dev

    - name: build tmux
      run: |
        curl -SL https://github.com/tmux/tmux/releases/download/3.0/tmux-3.0.tar.gz | tar -xzC .
        cd tmux-3.0
        ./configure --enable-static
        make -j$(nproc)
        ls

    - uses: actions/upload-artifact@v2
      with:
        name: tmux-binary
        path: tmux


